export const UPDATE_SCROLL = "UPDATE_SCROLL";
export const FIND_CONVERSATION = "FIND_CONVERSATION";
export const CREATE_CONVERSATION = "CREATE_CONVERSATION";
export const FLAG_CLOSE_CONVERSATION = "FLAG_CLOSE_CONVERSATION";
export const SHOW_CHAT = "SHOW_CHAT";
export const TOGGLE_STATE = "TOGGLE_STATE";
